### ISSUE TITLE
Rtwizard segmentation fault when running with no GUI

### ISSUE THREAD

**Issue by samhollenbeck** [BRL-CAD/brlcad#103]
`rtwizard m35.g component` and any other rtwizard command running without the GUI errors with segmentation fault.

Error:
`Segmentation fault: 11`

**Comment by starseeker** [comment]
Hi - this may already be fixed with one of today's commits to main - can you see if 98345360375cbd57dd963b2016ef94312c07d63a fixes the issue for you?

**Comment by samhollenbeck** [comment]
Yes, this was fixed. Thanks.
