### ISSUE TITLE
Why there are so few videos to learn Brl-Cad

### ISSUE THREAD

**Issue by AhmetAParker** [BRL-CAD/brlcad#124]
Hi,
I looked at Youtube and there is very few videos that teach little bit complex geometries on Brl-Cad. Is it possible for someone to make Brl-Cad learning videos (for both Mged and Archer)? Video tutorials on Brl-Cad will be very usefull. Please if you are going to do, make a little bit complex geometries. I think very simple ones do make you learn enough.

**Comment by brlcad** [comment]
It's possible for anyone to make BRL-CAD learning videos. That's a beauty (and achellies heel) of open source software.

Complex geometries in any CAD system require quite an investment of planning, effort, and time, so videos are not likely to happen without someone in the community stepping up to help do that.  If we have at least a transcript that someone could follow, we could plan for a future Season of Docs to create the videos.  Still quite a lot of work to do that, but that'd be a start.
