### ISSUE TITLE
translate and rotate from text file.

### ISSUE THREAD

**Issue by bentleyeglin** [BRL-CAD/brlcad#125]
I have a .g that was built from STL.  It has one region and the path is all/r.stl/s.stl
s.stl is not a solid, but rather a BOT Bag of Triangles.
I need to be able to translate and rotate this region from a text file: mged model.g < input.txt
*EDIT*
I am able to translate and now rotate
in my text file I have to translate:
e s.stl
sed s.stl
keypoint 0 0 0
tra 0 0 -1000
accept
push s.stl

to rotate the command is rot.  I'm rusty.

**Comment by brlcad** [comment]
I was going to say, you have to draw/e the object before you can sed it.  After doing that, either rot or orot should work.

**Comment by brlcad** [comment]
Also just a note -- it's only useful to set a keypoint for rotations.  It tells it which point to rotate about.  For translations it doesn't hurt, it just doesn't matter though either.
