### ISSUE TITLE
Kaspersky detect Trojan.Win32.Sdum.gen virus in BRL-CAD?!

### ISSUE THREAD

**Issue by miltoncsl** [BRL-CAD/brlcad#129]
Hi,

I downloaded BRL-CAD version 7.38.2 win64 from github site and when I started Kaspersky scan in brlcad installer to install later, Kaspersky detected Trojan.Win32.Sdum.gen in the "exe" extension installer!! I am applying now Kaspersky in my computer to make sure there aren't problem!! :(
![virus brl-cad](https://github.com/BRL-CAD/brlcad/assets/15256674/24d67efc-abe9-4f0a-beee-6d15b93f4cd1)

**Comment by brlcad** [comment]
Reports like this have come up before and they've always been a false positive.  BRL-CAD binaries are compiled in clean environments.  That is, the report is almost certainly wrong.  You can try submitting the file in question to https://opentip.kaspersky.com for more in-depth analysis.
