### ISSUE TITLE
geogram is marked as extra dependency

### ISSUE THREAD

**Issue by bylee20** [BRL-CAD/brlcad#158]
librt mandates geogram but geogram is marked as dependency for extra.
I think librt is not an library for BRLCAD_EXTRA.

**Comment by bylee20** [comment]
Or, when you compile librt, it adds -DUSE_GEOGRAM unconditionally and maybe this is the problem. I am not sure which one is correct here.
Anywat, for now, librt cannot be built without geogram.

* Remove geogram and make it optional dependency for librt
* Or, geogram should be marked as core dependency not an extra dependency.

**Comment by starseeker** [comment]
Ah, good catch - it was initially being tested using BRLCAD_EXTRA in bext, but at this point its being used as part of some fairly important commands so it should be marked as required.  I've updated its categorization in the bext repository - thanks!
