### ISSUE TITLE
/utf-8 flag should be set for MSVC build

### ISSUE THREAD

**Issue by bylee20** [BRL-CAD/brlcad#159]
some files, for instance, fort.c require UTF-8 encoded source code support which is disabled on MSVC by default.
You should append /utf-8 flag to enable UTF-8 source code support on MSVC.

**Comment by starseeker** [comment]
Interesting.  What version of Visual Studio are you using to build?  I don't think I've seen a UTF-8 build failure myself with MSVC...

**Comment by bylee20** [comment]
> Interesting. What version of Visual Studio are you using to build? I don't think I've seen a UTF-8 build failure myself with MSVC...

It is VS2022 but I don't think this is version specific problem.\
/utf-8 flag exists since VS2017 at least and it might be there in VS2015 too.

Maybe your codepage is compatible with UTF-8?
My codepage is CP949 which is not compatible with UTF-8 and MSVC uses the OS' codepage when dealing with encoding.

**Comment by starseeker** [comment]
Can you let us know if https://github.com/BRL-CAD/brlcad/commit/8012562f1d2445bbe4a00f608ff9467e7958e1f6 fixes your issue?

**Comment by bylee20** [comment]
Yes, thank you!
