### ISSUE TITLE
no option not to build test executables

### ISSUE THREAD

**Issue by bylee20** [BRL-CAD/brlcad#160]
I want to build libraries only but there's no such option.
It seems that the each build script unconditionally calls "add_subdirectory(tests)" and all test executables are always built and deployed.
It would be nice to have option to turn off build of any non-library files.

**Comment by starseeker** [comment]
It won't disable the test executables for the libraries, but you can use the BRLCAD_COMPONENTS variable to build a smaller subset of BRL-CAD if that helps.  For example:

cmake ../brlcad -DBRLCAD_COMPONENTS=librt && make -j8

will build only the parts needed for librt.

Probably we should key our test executable builds on the BUILD_TESTING variable CTest uses, but I'll have to do some testing to see what the implications are.

**Comment by bylee20** [comment]
I am already building BRLCAD with -DBRLCAD_COMPONENTS=libged.
I've just wanted to build less unnecessary files.

**Comment by starseeker** [comment]
I think https://github.com/BRL-CAD/brlcad/commit/a399cd39026eeda2b82676c085476c5d2ca955fa should do what you're looking for if you set -DBUILD_TESTING=OFF

**Comment by starseeker** [comment]
If you can tell us, what use case are you using the BRLCAD_COMPONENTS minimalist build for?  It's a very new feature, and you're the first user to try it out that I know of, so I'm curious to know how it is being used.

**Comment by bylee20** [comment]
> If you can tell us, what use case are you using the BRLCAD_COMPONENTS minimalist build for? It's a very new feature, and you're the first user to try it out that I know of, so I'm curious to know how it is being used.

I am a BRL-CAD library consumer for ray tracing instead of BRL-CAD application, so I don't need any GUI facilities.
As a matter of fact, I thought that I don't even need libged but some new features, especially new facetization in 7.40.0 seems only accessible through libged.

**Comment by bylee20** [comment]
I have tried latest revision but it still builds lots of test exec.
For instance, here
https://github.com/BRL-CAD/brlcad/blob/02ba341f2ea0c58c896a9224ec8c6ed7b434f6db/src/libbg/CMakeLists.txt#L106
all tests programs for libbg are unconditionally added to build list.
It seems many other test programs are same situation.

With BRLCAD_COMPONENTS=libged and BUILD_TESTING=OFF, here's the exe list which I get:
```

test_brep_ppx.exe
test_help.exe
tpkg.exe
analyze_densities.exe
analyze_nhit.exe
analyze_raydiff.exe
analyze_sp.exe
bg_chull.exe
bg_chull3d.exe
bg_lseg_lseg_dist.exe
bg_lseg_pt_dist.exe
bg_obr.exe
bg_polygon_op.exe
bg_polygon_triangulate.exe
bg_sat.exe
bg_test.exe
bg_tri_area.exe
bg_tri_closest_pt.exe
bg_tri_ray_isect.exe
bg_tri_tri_isect.exe
bg_tri_tri_isect_coplanar.exe
bg_trimesh_sync.exe
bgpoly2tri.exe
bgtester.exe
bn_eigen.exe
bn_randsph.exe
bn_test.exe
bu_dylib.exe
bu_gethostname.exe
bu_hash.exe
bu_progname.exe
bu_sscanf.exe
bu_subprocess.exe
bu_test.exe
bu_test_uuid.exe
bu_vls_incr_uniq.exe
bundle.exe
bview_plot3.exe
bview_test.exe
cad_user.exe
covgcheck.exe
db5_size.exe
debug2c.exe
dm_test.exe
echeck.exe
env2c.exe
fuzz_ged_test.exe
fuzz_shootray_test.exe
ged_exec.exe
ged_test_aet.exe
ged_test_draw.exe
ged_test_faceplate.exe
ged_test_gqa.exe
ged_test_list.exe
ged_test_lod.exe
ged_test_material.exe
ged_test_plugins.exe
ged_test_quad.exe
ged_test_search.exe
ged_test_select.exe
ged_test_select_draw.exe
ged_test_tops.exe
gen-attributes-file.exe
icv_crop.exe
icv_fade.exe
icv_filter.exe
icv_operations.exe
icv_read_write.exe
icv_rect.exe
icv_saturate.exe
icv_size_down.exe
icv_size_up.exe
nmg_test.exe
pkg_test_client.exe
pkg_test_server.exe
pngfix.exe
png-fix-itxt.exe
regress_mater.exe
regress_pkg.exe
regress_push.exe
repocheck.exe
rt_bv_poly_sketch.exe
rt_cache.exe
rt_cyclic.exe
rt_diff.exe
rt_dvec.exe
rt_lod.exe
rt_nurbs_tester.exe
rt_pattern.exe
rt_search_test.exe
rt_ssi.exe
```

Some exes like getd_exec are not test program I guess most of them are test only purpose programs.

**Comment by starseeker** [comment]
Correct, ged_exec is not a test program.  It's used by libged to launch commands as subprocesses when we need to be able to terminate them based on time-out.

Hmm.  With a latest "main" branch checkout on Linux, and the following configure:
```
cmake .. -G Ninja -DBRLCAD_COMPONENTS=libged -DBUILD_TESTING=OFF
```

I get the following in bin:
```
~/brlcad/build (main) $ ls bin/
db_dir_info  debug2c  env2c  ged_exec  pngfix  png-fix-itxt
```

I'll have to try on Windows and see if there's a problem there.

**Comment by starseeker** [comment]
Couple minor things, and a few more executable files coming from dependencies, but I do seem to be getting a minimalist build on Windows as well with latest main.  Can you paste your exact CMake line?

**Comment by bylee20** [comment]
I have just tried again and now I get only few exes. I don't understand what happended but maybe some old cmake cache did bad things.
Now I get:

```
ged_exec.exe
env2c.exe
debug2c.exe
test_brep_ppx.exe
png-fix-itxt.exe
pngfix.exe
gen-attributes-file.exe
```

I think this list is small enough to ignore build resource now.
Thank you for your effort and sorry to bother you with wrong information.

FYI, I am using `CMakePresets.json` instead of full command line options and, here it is:

```
{
  "version": 3,
  "configurePresets": [
    {
      "name": "brlcad_default",
      "hidden": false,
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "CMAKE_INSTALL_PREFIX": "${sourceDir}/../brlcad-install",
        "BUILD_TESTING": "OFF",
        "BRLCAD_EXT_DIR": "${sourceDir}/../bext_output",
        "BRLCAD_ENABLE_MINIMAL": "ON",
        "BRLCAD_ENABLE_GDAL": "OFF",
        "BRLCAD_ENABLE_TCL": "OFF",
        "BRLCAD_COMPONENTS": "libged"
      }
    }
  ]
}
```
