### ISSUE TITLE
3d only or support also 2d

### ISSUE THREAD

**Issue by vehosah** [BRL-CAD/brlcad#25]
Brl cad can be used only for 3d or we can use it also with 2d?

**Comment by brlcad** [comment]
There is support for 2D in BRL-CAD.  One can import 2D sketch entities using the DXF importer.  One can create 2D sketch entities in MGED/Archer using a graphical sketch editor GUI.  One can create 2D sketch objects on the command line too (see https://brlcad.org/wiki/Sketch).  Sketch objects can be extruded to 3D (see https://brlcad.org/wiki/Extrude).  Extruded sketches are fully supported for ray trace rendering and polygonal export to other formats.

That said, you might want to check out LibreCAD as it directly caters to 2D modeling.
