### ISSUE TITLE
problems with mged

### ISSUE THREAD

**Issue by H2Birk** [BRL-CAD/brlcad#67]
Hey there, if I want to start mged, the GUI won't open. Instead it shows this message (Ubuntu 22.04.2):

BRL-CAD Release 7.34.3  Geometry Editor (MGED)
    Mon, 20 Mar 2023 11:53:30 UTC, Compilation 0
    lukas@lukas-Latitude-E6520

attach (nu ps txt)[nu]? 

What should I do there?

The second question is how to delete brl-cad.

Thanks for your help

**Comment by brlcad** [comment]
That looks like you compiled BRL-CAD without X11 support.  You can find a lot of platform-specific details about what dependencies are required for Ubuntu at https://brlcad.org/wiki/Compiling 

As for deleting BRL-CAD, it's as simple as deleting the directory where you're compiling or where you installed to.  Default should have been /usr/brlcad/dev-7.34.3 so you can delete /usr/brlcad to remove the installation.
