### ISSUE TITLE
Does it support opening solidworks models?

### ISSUE THREAD

**Issue by yanchiuvip** [BRL-CAD/brlcad#96]
Does it support import and export of some commercial CAD format files

**Comment by starseeker** [comment]
Not directly, no.  We support importing some of the conversion formats like STEP AP203 and IGES, but we can't directly read the commercial formats.  There is a Creo plugin that enhances Creo to export BRL-CAD .g files, but that requires Creo to run.

**Comment by starseeker** [comment]
Not directly, no.  We support importing some of the conversion formats like STEP AP203 and IGES, but we can't directly read the commercial formats.  There is a Creo plugin that enhances Creo to export BRL-CAD .g files, but that requires Creo to run.
